#  Make WWW under unix for rs6000 with no gcc
#
# This directory:
HERE = /u/timbl/userd/tbl/hypertext/WWW/LineMode/Implementation/rs6000

# The directory with the deafult home page in:
DEFAULTS = /u/timbl/userd/tbl/hypertext/WWW/LineMode/Defaults

# Directory for installed binary:
BINDIR = /usr/local/bin

CMN = ../../../Implementation/
LM = ../

#CFLAGS = -I$(CMN) -I$(LM) -DDEBUG
CFLAGS = -I$(CMN) -I$(LM) -g  -DDEBUG 

CC = cc

include $(LM)CommonMakefile
	

